"""Create Meeting table

Revision ID: 50dfe215342a
Revises: 140581e8aca2
Create Date: 2026-01-24 10:52:21.810310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50dfe215342a'
down_revision: Union[str, Sequence[str], None] = '140581e8aca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('life_time', sa.DateTime(), nullable=False),
    sa.Column('input_time', sa.DateTime(), nullable=False),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.Column('edu_year_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['edu_year_id'], ['eduyears.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    # ### end Alembic commands ###
